### PR TITLE
Fix timer count

### LINKED ISSUE #142: Incorrect rate
Hi,

I've noticed that the rate is calculated incorrectly for counters and timers when used with a sample rate.

For example:

```js
setInterval(function() {
  statsite.timing('statsite', 100);
  statsite.timing('statsite.sampled', 100, 0.5);
}, 100);
```

This sends two timers, one sampled and one not. The rate of both should, I believe, be 10 as an event is sent every 100ms. However, the rate for the sampled timer is coming out at around 5.

I think the issue is that the timer count is always incremented by 1:

https://github.com/armon/statsite/blob/master/src/timer.c#L40

Where in actual fact it should be incremented by `1 / sampleRate`:

https://github.com/etsy/statsd/blob/master/stats.js#L259

Would you accept a PR that changes this to be compatible with StatsD?

### PR DESCRIPTION
**Pull request by nspragg**
fixes #142 

Simple example test using netcat: Executed these in succession
echo "foo:5|ms|@0.5" | nc -u -w0 127.0.0.1
echo "foo:5|ms|@0.5" | nc -u -w0 127.0.0.1
echo "foo:5|ms|@0.5" | nc -u -w0 127.0.0.1
echo "foo:5|ms|@0.5" | nc -u -w0 127.0.0.1

Output from custom sink script:

Before:
'timers.foo.count|4|1439367451’,
'timers.foo.mean|5.000000|1439367451',
'timers.foo.sample_rate|0.400000|1439367451’,

After:
'timers.foo.count|8|1439365840’,
'timers.foo.mean|5.000000|1439365840’,
'timers.foo.sample_rate|0.800000|1439365840’,

### CODE REVIEW

File: src/conn_handler.c [hunk 1]
```diff
@@ -460,21 +462,23 @@ static int handle_ascii_client_connect(statsite_conn_handler *handle) {
...
-        if (type == COUNTER && !buffer_after_terminator(type_str, after_len, '@', &sample_str, &after_len)) {
+        // Handle counter/timer sampling if applicable
+        if ((type == COUNTER || type == TIMER) && !buffer_after_terminator(type_str, after_len, '@', &sample_str, &after_len)) {
             sample_rate = str2double(sample_str, &endptr);
-            if (unlikely(endptr == sample_str)) {
-                syslog(LOG_WARNING, "Failed sample rate conversion! Input: %s", sample_str);
-                goto ERR_RET;
-            }
-            if (sample_rate > 0 && sample_rate <= 1) {
+            if (type == COUNTER) {
```
Comment (armon) [inline src/conn_handler.c]: This should probably guard the value maximization, since we still want to check for the error in the TIMER case

File: src/metrics.c [hunk 2]
```diff
@@ -213,7 +214,7 @@ static int metrics_set_gauge(metrics *m, char *name, double val, bool delta) {
  * @arg val The sample to add
  * @return 0 on success.
  */
-int metrics_add_sample(metrics *m, metric_type type, char *name, double val) {
+int metrics_add_sample(metrics *m, metric_type type, char *name, double val, double sample_rate) {
```
Comment (armon) [inline src/metrics.c]: This should probably be used for the COUNTER type as well

File: src/timer.h [hunk 3]
```diff
@@ -4,7 +4,8 @@
 #include "cm_quantile.h"
 
 typedef struct {
-    uint64_t count;     // Count of items
+    uint16_t actual_count; // Actual items recieved
```
Comment (armon) [inline src/timer.h]: Lets make this an `uint64_t` since it is pretty easy to overflow a `uint16_t` within statsite

**Comment by armon** [comment]
@nspragg Left some minor feedback, looking good!

File: src/timer.h (hunk 3 above)
Comment (nspragg) [inline src/timer.h]: My bad. This was unintentional. Should definitely be uint64_t like count.

File: src/conn_handler.c (hunk 1 above)
Comment (nspragg) [inline src/conn_handler.c]: Good point - will add guard for both counter and timer.

File: src/metrics.c (hunk 2 above)
Comment (nspragg) [inline src/metrics.c]: Just to clarify: do you mean update 'metrics_increment_counter' to accept a sample_rate? 

If so, are you ok for me to investigate and make this change in another pr, specifically addressing the counter type?

Comment (armon) [inline src/metrics.c]: @nspragg Yeah we can do it in a new PR, but for the increment counter as you said

File: src/conn_handler.c [hunk 4]
```diff
@@ -460,21 +462,25 @@ static int handle_ascii_client_connect(statsite_conn_handler *handle) {
...
+        if ((type == COUNTER || type == TIMER) && !buffer_after_terminator(type_str, after_len, '@', &sample_str, &after_len)) {
+            double unchecked_rate = str2double(sample_str, &endptr);
             if (unlikely(endptr == sample_str)) {
                 syslog(LOG_WARNING, "Failed sample rate conversion! Input: %s", sample_str);
                 goto ERR_RET;
             }
-            if (sample_rate > 0 && sample_rate <= 1) {
-                // Magnify the value
-                val = val * (1.0 / sample_rate);
+            if (unchecked_rate > 0 && unchecked_rate <= 1) {
```
Comment (armon) [inline src/conn_handler.c]: we can use the `likely` macro here since most inputs should be valid.

**Comment by armon** [comment]
Looks great!
